services:

  axum:
    image: rust-axum-url-shortener
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          memory: 512MB
          cpus: 1.0
    environment:
      PG_CONNECTION_STRING: host=db user=admin password=admin dbname=url_shortener

  quarkus:
    image: quarkus-url-shortener:jvm
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 512MB
          cpus: 1.0
    environment:
      quarkus.profile: prod
      quarkus.log.level: WARN
      quarkus.datasource.db-kind: postgresql
      quarkus.datasource.username: admin
      quarkus.datasource.password: admin
      quarkus.datasource.reactive.url: postgresql://db:5432/url_shortener

  db:
    image: postgres:16
    tmpfs: /data/postgres
    environment:
      POSTGRES_DB: "url_shortener"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
