[package]
name = "rust-axum-url-shortener"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
tokio = { version = "1.38.0", features = ["full"] }
tokio-postgres = "0.7.10"
bb8 = "0.8.3"
bb8-postgres = "0.8.1"
serde = { version = "1.0.203", features = ["derive"] }
